// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace BBK_A2_SWE5201_2201525.Data.BBKDB;

public partial class BBKDBContext : DbContext
{
    public BBKDBContext(DbContextOptions<BBKDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Bike> Bike { get; set; }

    public virtual DbSet<Course> Course { get; set; }

    public virtual DbSet<Cyclist> Cyclist { get; set; }

    public virtual DbSet<Part> Part { get; set; }

    public virtual DbSet<Repair> Repair { get; set; }

    public virtual DbSet<Volunteer> Volunteer { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Bike>(entity =>
        {
            entity.HasKey(e => e.BikeId).HasName("PK__Bike__7DC817215E7DC0F7");

            entity.Property(e => e.BikeModel).HasMaxLength(255);

            entity.HasOne(d => d.Cyclist).WithMany(p => p.Bike)
                .HasForeignKey(d => d.CyclistId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("db_CyclistBike");
        });

        modelBuilder.Entity<Course>(entity =>
        {
            entity.HasKey(e => e.CourseId).HasName("PK__Course__C92D71A78B27904F");

            entity.Property(e => e.CourseName).HasMaxLength(255);

            entity.HasOne(d => d.Volunteer).WithMany(p => p.Course)
                .HasForeignKey(d => d.VolunteerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("db_VolunteerCourse");
        });

        modelBuilder.Entity<Cyclist>(entity =>
        {
            entity.HasKey(e => e.CyclistId).HasName("PK__Cyclist__A3CBF980CDB37CA1");

            entity.Property(e => e.Address).HasMaxLength(255);
            entity.Property(e => e.Email).HasMaxLength(255);
            entity.Property(e => e.FirstName).HasMaxLength(50);
            entity.Property(e => e.LastName).HasMaxLength(50);
            entity.Property(e => e.PhoneNumber).HasMaxLength(11);

            entity.HasOne(d => d.Course).WithMany(p => p.Cyclist)
                .HasForeignKey(d => d.CourseId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("db_CourseCyclist");
        });

        modelBuilder.Entity<Part>(entity =>
        {
            entity.HasKey(e => e.PartId).HasName("PK__tmp_ms_x__7C3F0D506877722B");

            entity.Property(e => e.PartCost)
                .HasMaxLength(5)
                .IsUnicode(false);
            entity.Property(e => e.PartName)
                .HasMaxLength(255)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Repair>(entity =>
        {
            entity.HasKey(e => e.RepairId).HasName("PK__Repair__07D0BC2DA628D58B");

            entity.Property(e => e.RepairType)
                .HasMaxLength(255)
                .IsUnicode(false);

            entity.HasOne(d => d.Bike).WithMany(p => p.Repair)
                .HasForeignKey(d => d.BikeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("db_BikeRepair");

            entity.HasOne(d => d.Part).WithMany(p => p.Repair)
                .HasForeignKey(d => d.PartId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("db_PartRepair");

            entity.HasOne(d => d.Volunteer).WithMany(p => p.Repair)
                .HasForeignKey(d => d.VolunteerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("db_VolunteerRepair");
        });

        modelBuilder.Entity<Volunteer>(entity =>
        {
            entity.HasKey(e => e.VolunteerId).HasName("PK__tmp_ms_x__716F6F2C1720D3B5");

            entity.Property(e => e.VolunteerAddress)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.VolunteerEmail)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.VolunteerForename)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.VolunteerPhoneNumber)
                .HasMaxLength(11)
                .IsUnicode(false);
            entity.Property(e => e.VolunteerSurname)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}