// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BBK_A2_SWE5201_2201525.Data.BBKDB;

public partial class Course
{
    public int CourseId { get; set; }

    public string CourseName { get; set; }

    public int VolunteerId { get; set; }

    public virtual ICollection<Cyclist> Cyclist { get; set; } = new List<Cyclist>();

    public virtual Volunteer Volunteer { get; set; }
}