// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BBK_A2_SWE5201_2201525.Data.BBKDB;

public partial class Cyclist
{
    public int CyclistId { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string PhoneNumber { get; set; }

    public string Email { get; set; }

    public string Address { get; set; }

    public int CourseId { get; set; }

    public virtual ICollection<Bike> Bike { get; set; } = new List<Bike>();

    public virtual Course Course { get; set; }
}