// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BBK_A2_SWE5201_2201525.Data.BBKDB;

public partial class Part
{
    public int PartId { get; set; }

    public string PartName { get; set; }

    public string PartCost { get; set; }

    public virtual ICollection<Repair> Repair { get; set; } = new List<Repair>();
}