// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BBK_A2_SWE5201_2201525.Data.BBKDB;

public partial class Volunteer
{
    public int VolunteerId { get; set; }

    public string VolunteerForename { get; set; }

    public string VolunteerSurname { get; set; }

    public string VolunteerPhoneNumber { get; set; }

    public string VolunteerEmail { get; set; }

    public string VolunteerAddress { get; set; }

    public virtual ICollection<Course> Course { get; set; } = new List<Course>();

    public virtual ICollection<Repair> Repair { get; set; } = new List<Repair>();
}